#:schema https://raw.githubusercontent.com/rogue-sly/dotbee/refs/heads/main/schema/dotbee.json

[settings]
auto_detect_profile = true
on_conflict = "ask"

[global.links]
"~/.config/fastfetch" = "./profiles/global/fastfetch"
"~/.config/git" = "./profiles/global/git"
"~/.config/nvim" = "./profiles/global/nvim/"
"~/.config/vim" = "./profiles/global/vim/"
"~/.config/zellij" = "./profiles/global/zellij"
"~/.local/share/wallpapers" = "./wallpapers"

[profiles.den.links]
"~/.config/alacritty" = "./profiles/laptop/user/alacritty"
"~/.config/fish" = "./profiles/laptop/user/fish"
"~/.config/godot" = "./profiles/laptop/user/godot"
"~/.config/inlyne" = "./profiles/laptop/user/inlyne"
"~/.config/kitty" = "./profiles/laptop/user/kitty"
"~/.config/mise" = "./profiles/laptop/user/mise"
"~/.config/ripgrep" = "./profiles/laptop/user/ripgrep"
"~/.npmrc" = "./profiles/laptop/user/.npmrc"

[profiles.termux.links]
"~/.config/fish" = "./profiles/termux/fish"
"~/.termux" = "./profiles/termux/termux-settings"
