#:schema https://raw.githubusercontent.com/rogue-sly/dotbee/refs/heads/main/schema/dotbee.json

[vars]
cfg = "~/.config"
global = "./profiles/global"
den = "./profiles/den"
termux = "./profiles/termux"

[profiles.global.links]
fastfetch = { dst = "{cfg}/fastfetch", src = "{global}/fastfetch" }
git = { dst = "{cfg}/git", src = "{global}/git" }
nvim = { dst = "{cfg}/nvim", src = "{global}/nvim/" }
vim = { dst = "{cfg}/vim", src = "{global}/vim/" }
zellij = { dst = "{cfg}/zellij", src = "{global}/zellij" }
wallpapers = { dst = "~/.local/share/wallpapers", src = "wallpapers" }

[profiles.den.links]
alacritty = { dst = "{cfg}/alacritty", src = "{den}/user/alacritty" }
fish = { dst = "{cfg}/fish", src = "{den}/user/fish" }
godot = { dst = "{cfg}/godot", src = "{den}/user/godot" }
inlyne = { dst = "{cfg}/inlyne", src = "{den}/user/inlyne" }
kitty = { dst = "{cfg}/kitty", src = "{den}/user/kitty" }
mise = { dst = "{cfg}/mise", src = "{den}/user/mise" }
rg = { dst = "{cfg}/ripgrep", src = "{den}/user/ripgrep" }
npmrc = { dst = "~/.npmrc", src = "{den}/user/.npmrc" }

[profiles.termux.links]
fish = { dst = "{cfg}/fish", src = "{termux}/fish" }
termux = { dst = "~/.termux", src = "{termux}/termux-settings" }
