#:schema https://raw.githubusercontent.com/rogue-sly/dotbee/refs/heads/main/schema/dotbee.json

[vars]
cfg = "~/.config"
global = "./profiles/global"
den = "./profiles/den"
termux = "./profiles/termux"

[profiles.global.links]
fastfetch = { src = "{global}/fastfetch", dst = "{cfg}/fastfetch" }
git = { src = "{global}/git", dst = "{cfg}/git" }
nvim = { src = "{global}/nvim/", dst = "{cfg}/nvim" }
vim = { src = "{global}/vim/", dst = "{cfg}/vim" }
zellij = { src = "{global}/zellij", dst = "{cfg}/zellij" }
wallpapers = { src = "wallpapers", dst = "~/.local/share/wallpapers" }

[profiles.den.links]
alacritty = { src = "{den}/user/alacritty", dst = "{cfg}/alacritty" }
fish = { src = "{den}/user/fish", dst = "{cfg}/fish" }
godot = { src = "{den}/user/godot", dst = "{cfg}/godot" }
inlyne = { src = "{den}/user/inlyne", dst = "{cfg}/inlyne" }
kitty = { src = "{den}/user/kitty", dst = "{cfg}/kitty" }
mise = { src = "{den}/user/mise", dst = "{cfg}/mise" }
rg = { src = "{den}/user/ripgrep", dst = "{cfg}/ripgrep" }
npmrc = { src = "{den}/user/.npmrc", dst = "~/.npmrc" }

[profiles.termux.links]
fish = { src = "{termux}/fish", dst = "{cfg}/fish" }
termux = { src = "{termux}/termux-settings", dst = "~/.termux" }
