#:tombi toml-version = "v1.1.0"

[tools]
"aqua:VirusTotal/vt-cli" = "latest"
"aqua:bahdotsh/wrkflw" = "latest"
"github:RivoLink/leaf" = "latest"
"github:Y2Z/monolith" = "latest"
"github:mroboff/vm-curator" = "latest"
"github:rogue-sly/dotbee" = "latest"
"github:scipenai/tylax" = "latest"
"npm:@mermaid-js/mermaid-cli" = "latest"
actionlint = "latest"
git-cliff = "latest"
lazygit = "latest"
lefthook = "latest"
opencode = "latest"
usql = "latest"
zk = "latest"

# lsp
"cargo:neocmakelsp" = "latest"
"dotnet:roslyn-language-server" = { version = "latest", prerelease = true }
"github:JCWasmx86/MesonLSP" = "latest"
"github:latex-lsp/texlab" = "latest"
"npm:@vtsls/language-server" = "latest"
lua-language-server = "latest"
tinymist = "latest"
tombi = "latest"

# fmt
oxfmt = "latest"
stylua = "latest"

[settings]
auto_install = false
disable_tools = [
  "dotnet",
  "node",
  "rust",
  "uv",
]
locked = true
lockfile = true
# backends
cargo = { binstall = true }
pipx = { uvx = true }
