[tools]
# lsp
"github:DanielGavin/ols" = "latest"
"github:OmniSharp/omnisharp-roslyn" = "latest"  # dotnet version < 10
"dotnet:roslyn-language-server" = { version = "latest", prerelease = true }  # dotnet version >= 10
"github:latex-lsp/texlab" = "latest"
lua-language-server = "latest"
tinymist = "latest"
tombi = "latest"
# fmt
oxfmt = "latest"
stylua = "latest"
# etc
"github:zk-org/zk" = "latest"
