[tools]
# lsp
"github:DanielGavin/ols" = "latest"
"dotnet:roslyn-language-server" = { version = "latest", prerelease = true }
"github:latex-lsp/texlab" = "latest"
lua-language-server = "latest"
tinymist = "latest"
tombi = "latest"
# fmt
oxfmt = "latest"
stylua = "latest"
# etc
"github:zk-org/zk" = "latest"
