call plug#begin('~/.config/vim/plugged')
  Plug 'puremourning/vimspector'
call plug#end()

" vimspector
let g:vimspector_enable_mappings = 'HUMAN'   	" F5 continue, F10 step over, F11 step into, Shift+F5 stop
nmap <Leader>di <Plug>VimspectorBalloonEval 	" inspect value under cursor
xmap <Leader>di <Plug>VimspectorBalloonEval    	" inspect selected text

colorscheme habamax
