# CORE #
cursor_trail 0
disable_ligatures never
enable_audio_bell no
pixel_scroll yes
placement_strategy center
shell fish

# FONT #
font_size        14
font_family      JetBrainsMono Nerd Font
bold_font        JetBrainsMono Nerd Font Bold
italic_font      JetBrainsMono Nerd Font Italic
bold_italic_font JetBrainsMono Nerd Font Bold Italic

# TABS #
active_tab_font_style   bold-italic
inactive_tab_font_style normal
tab_bar_edge bottom
tab_bar_margin_height 0.0 0.0
tab_bar_margin_width  0.0
tab_bar_min_tabs 2
tab_bar_style separator
tab_separator "   ┇   "
tab_switch_strategy previous
tab_title_max_length 10


# KEYMAPS #
map ctrl+shift+enter new_window_with_cwd
map ctrl+shift+t new_tab_with_cwd
