#!/usr/bin/env bash
#MISE description="Upgrade system and install packages"
set -euo pipefail

packages=(
    # cli/tui
    btop
    curl
    fastfetch
    fd-find
    jq
    tealdeer
    tree
    unzip
    wget
    which
    zellij
    zoxide
    # editor + tools
    git mise fzf lazygit ripgrep
    neovim neovim-default-editor
    zed
    # languages + package-managers
    dotnet-sdk-10.0 dotnet-sdk-8.0
    nodejs
    python3-pip python3-uv
    rustup
    # user-shell
    fish
)

sudo dnf upgrade -y --refresh

sudo dnf install "${packages[@]}"

sudo dnf autoremove -y
sudo dnf clean all
