[general]
import = ["~/.config/alacritty/themes/tokyonight/night.toml"]

[window]
dynamic_padding = false
decorations = "Full"
startup_mode = "Maximized"

[font]
normal = { family = "JetBrainsMono Nerd Font", style = "Regular" }
size = 14.0

[cursor]
style = { shape = "Block", blinking = "Off" }
vi_mode_style = { shape = "Beam", blinking = "On" }

[terminal]
shell = { program = "fish", args = ["-l", "-c", "zellij"] }
