[tools]
"github:RivoLink/leaf" = "latest"
"github:bahdotsh/wrkflw" = "latest"
"github:mroboff/vm-curator" = "latest"
"github:rogue-sly/dotbee" = "latest"
"github:scipenai/tylax" = "latest"
"github:zk-org/zk" = "latest"
git-cliff = "latest"
lefthook = "latest"
odin = "dev-2026-07a"

# lsp
"cargo:neocmakelsp" = "latest"
"dotnet:roslyn-language-server" = { version = "latest", prerelease = true }
"github:DanielGavin/ols" = { version = "latest", rename_exe = { "ols-*" = "ols", "odinfmt-*" = "odinfmt" } }
"github:JCWasmx86/MesonLSP" = "latest"
"github:latex-lsp/texlab" = "latest"
"npm:@vtsls/language-server" = "latest"
lua-language-server = "latest"
tinymist = "latest"
tombi = "latest"
# fmt
oxfmt = "latest"
stylua = "latest"

[settings]
auto_install = false
disable_tools = [
  "dotnet",
  "node",
  "rust",
  "uv",
  "python",
]
lockfile = true
# backends
cargo = { binstall = true }
pipx = { uvx = true }
