[tools]
"github:RivoLink/leaf" = "latest"
"github:bahdotsh/wrkflw" = "latest"
"github:exercism/cli" = "latest"
"github:mroboff/vm-curator" = "latest"
"github:rogue-sly/dotbee" = "latest"
"github:scipenai/tylax" = "latest"
"github:zk-org/zk" = "latest"
cargo-binstall = "latest"
dotnet = "latest"
gh = "latest"
git-cliff = "latest"
lefthook = "latest"
odin = "dev-2026-07a"

# lsp
"dotnet:roslyn-language-server" = { version = "latest", prerelease = true }
"github:DanielGavin/ols" = { version = "latest", rename_exe = { "ols-*" = "ols", "odinfmt-*" = "odinfmt" } }
"github:latex-lsp/texlab" = "latest"
"github:JCWasmx86/MesonLSP" = "latest"
lua-language-server = "latest"
tinymist = "latest"
tombi = "latest"
# fmt
oxfmt = "latest"
stylua = "latest"

[settings]
auto_install = false
lockfile = true
# backends
cargo = { binstall = true }
dotnet = { cli_telemetry_optout = true, isolated = true }
pipx = { uvx = true }
