#!/usr/bin/env bash
#MISE description="Enable OpenH264 codec repo in DNF"
set -euo pipefail
# configure dnf
sudo dnf config-manager setopt fedora-cisco-openh264.enabled=1

RELEASE=$(rpm -E %fedora)

# add dnf repos
sudo dnf install -y \
    "https://mirrors.rpmfusion.org/free/fedora/rpmfusion-free-release-${RELEASE}.noarch.rpm" \
    "https://mirrors.rpmfusion.org/nonfree/fedora/rpmfusion-nonfree-release-${RELEASE}.noarch.rpm"

sudo dnf install --nogpgcheck \
    --repofrompath "terra,https://repos.fyralabs.com/terra${RELEASE}" \
    terra-release

for copr in \
    "brycensranch/gpu-screen-recorder-git" \
    "roguedotsly/pixelorama" \
    "roguedotsly/trenchbroom"; do
    sudo dnf copr enable -y "$copr"
done

# install packages
packages=(
    kitty
    # cli/tui
    7zip
    btop
    curl
    direnv
    fastfetch
    fd-find
    jq
    tealdeer
    tree
    unzip
    wget
    which
    zellij
    zoxide
    # editor + tools
    neovim neovim-default-editor zed
    git mise fzf lazygit ripgrep ov git-delta
    # languages + package-managers
    dotnet-sdk-10.0 dotnet-sdk-8.0
    nodejs
    python3-pip python3-uv
    rustup
    # containers
    podman podman-compose podman-docker
    # multimedia codecs (RPM Fusion)
    ffmpeg gstreamer1-plugins-good-extras gstreamer1-plugins-bad-free-extras
    gstreamer1-plugins-ugly gstreamer1-libav gstreamer1-vaapi libva-utils
    # user-shell
    fish
)

groups=(
    development-tools
    c-development
    rpm-development-tools
)

sudo dnf upgrade -y --refresh

sudo dnf group install -y "${groups[@]}"

sudo dnf swap -y ffmpeg-free ffmpeg --allowerasing

sudo dnf install "${packages[@]}"

sudo dnf autoremove -y
sudo dnf clean all
