#!/usr/bin/env bash
#MISE description="Set up dotfiles via dotbee"
#MISE depends=["fedora:services"]
set -euo pipefail

mise install github:rogue-sly/dotbee
mise x github:rogue-sly/dotbee -- dotbee switch --profile den
